---
kind: pipeline
type: docker
name: main-pipeline

steps:
  - name: cargo-fmt
    image: casperlabs/casper-node-launcher-build
    commands:
      - rustup update stable
      - cargo fmt -- --check

  - name: cargo-clippy
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo clippy -- --deny warnings

  - name: cargo-audit
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo audit --deny warnings

  - name: test
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo test

  - name: build-deb
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo deb

trigger:
  branch:
    - main
    - trying
    - staging
    - "release-*"
  event:
    exclude:
      - tag

---
kind: pipeline
type: docker
name: failed-main

clone:
  disable: true

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template:
        - |
          casper-node-launcher build status: *{{ uppercasefirst build.status }}*
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
    - failure
  branch:
    - main
    - trying
    - staging
    - "release-*"
  event:
    exclude:
      - tag

depends_on:
  - main-pipeline
---
kind: pipeline
type: docker
name: release-by-tag

steps:
  - name: build-deb
    image: casperlabs/casper-node-launcher-build
    commands:
      - cargo deb

  - name: publish-bintray
    image: casperlabs/casper-node-launcher-build
    commands:
      - "./upload_to_bintray.sh --repo-name debian --package-name casper-node-launcher --package-tag true"
    environment:
      CL_VAULT_TOKEN:
        from_secret: vault_token
      CL_VAULT_HOST:
        from_secret: vault_host

  - name: build-casper-node-launcher-build
    image: docker:stable
    commands:
      - apk add git bash
      - ./ci/build_docker.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: push-docker
    image: docker:stable
    commands:
      - apk add git bash
      - ./ci/push-docker.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - docker_username
      - docker_password

trigger:
  ref:
    - refs/tags/v*
---
kind: pipeline
type: docker
name: failed-publish

clone:
  disable: true

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template:
        - |
          casper-node-launcher build status: *{{ uppercasefirst build.status }}*
          Author: {{ build.author }}
          Drone Build: <{{ build.link }}|#{{ build.number }}>
          Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
    - failure
  ref:
    - refs/tags/v*

depends_on:
  - release-by-tag
