[package]
name = "casper-node-launcher"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "A binary which runs and upgrades the casper-node of the Casper network"
readme = "README.md"
documentation = "https://docs.rs/casper-node-launcher"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/client"
license-file = "../LICENSE"

[dependencies]
anyhow = "1.0.38"
clap = "3.0.0-beta.2"
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.120", features = ["derive"] }
toml = "0.5.8"
tracing = "0.1.22"
tracing-subscriber = { version = "0.2.15", features = ["json"] }

[dev-dependencies]
once_cell = "1.5.2"
tempfile = "3.2.0"


[package.metadata.deb]
features = ["vendored-openssl"]
revision = "0"
depends = "curl"
assets = [
    ["./target/release/casper-node-launcher", "/usr/bin/casper-node-launcher", "755"],
    ["./resources/BIN_README.md", "/var/lib/casper/bin/README.md", "755"],
    ["./resources/maintainer_scripts/logrotate.d/casper-node", "/etc/logrotate.d/casper-node", "644"],
    ["./resources/maintainer_scripts/pull_casper_node_version.sh", "/etc/casper/pull_casper_node_version.sh", "755"],
    ["./resources/maintainer_scripts/delete_local_db.sh", "/etc/casper/delete_local_db.sh", "755"],
    ["./resources/maintainer_scripts/config_from_example.sh", "/etc/casper/config_from_example.sh", "755"],
    ["./resources/DEB_README.md", "/etc/casper/README.md", "644"],
    ["./resources/validator_keys/README.md", "/etc/casper/validator_keys/README.md", "644"]
]
maintainer-scripts = "../resources/maintainer_scripts/debian"
extended-description = """
Package for Casper Node and Client.

For information on using package, see https://github.com/CasperLabs/casper-node
"""

[package.metadata.deb.systemd-units]
unit-scripts = "../resources/maintainer_scripts/casper_node"
restart-after-upgrade = false